version: "3.5"

services:
  cron-downloader:
    image: cron-downloader:latest
    build: .
    environment:
      UTIL_CRON_SCHEDULER_CONFIG_PATH: file:///opt/config.json
      UTIL_CRON_DOWNLOAD_DIRECTORY: /var/output
    container_name: cron-downloader
    restart: always
    volumes: 
      - ${LOCAL_CONFIG_PATH}:/opt/config.json:ro
      - ${LOCAL_OUT_PATH}:/var/output
